// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "f6224ece-ff74-4929-a13b-b93c92b89287");
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1788318151);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1788318150);
user_pref("app.update.lastUpdateTime.suggest-ingest", 1788318149);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "221afee5-7d53-4bae-acb4-3183ce48b8b0");
user_pref("browser.contextual-services.contextId.timestamp-in-seconds", 1788318148);
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.ipProtection.added", true);
user_pref("browser.ipProtection.enabled", true);
user_pref("browser.ipProtection.stateCache", "unauthenticated");
user_pref("browser.ipProtection.usageCache", "");
user_pref("browser.migration.version", 177);
user_pref("browser.ml.chat.nimbus", "copilot-chatbot-sunset:control");
user_pref("browser.newtabpage.activity-stream.impressionId", "{b1b796f7-fcc2-44e6-8d99-755d80a04b29}");
user_pref("browser.newtabpage.activity-stream.newtabWallpapers.user.enabled.migrated", true);
user_pref("browser.newtabpage.activity-stream.widgets.sportsWidget.enabled", false);
user_pref("browser.newtabpage.activity-stream.widgets.sportsWidget.pollLiveMs", 60000);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.newtabpage.trainhopAddon.version", "156.2.20260824.60102");
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.preonboarding.splashShown", true);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1788318147);
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1788318150400");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1788339750400");
user_pref("browser.search.experiment", "startpage-message");
user_pref("browser.search.region", "DE");
user_pref("browser.search.serpEventTelemetryCategorization.regionEnabled", false);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1788318148");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.lastColdStartupCheck", 1788318149);
user_pref("browser.termsofuse.prefMigrationCheck", true);
user_pref("browser.theme.toolbar-theme", 0);
user_pref("browser.toolbarbuttons.introduced.sidebar-button", true);
user_pref("browser.topsites.contile.cacheValidFor", 10800);
user_pref("browser.topsites.contile.lastFetch", 1788318149);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[],\"nav-bar\":[\"sidebar-button\",\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"vertical-spacer\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"ipprotection-button\",\"fxa-toolbar-menu-button\",\"reset-pbm-toolbar-button\",\"unified-extensions-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\",\"ai-window-toggle\"],\"vertical-tabs\":[],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"reset-pbm-toolbar-button\",\"ai-window-toggle\",\"developer-button\",\"screenshot-button\",\"ipprotection-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"vertical-tabs\"],\"currentVersion\":25,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 7);
user_pref("captchadetection.lastSubmission", 1788318);
user_pref("datareporting.dau.cachedUsageProfileGroupID", "a05a3908-2eb4-44b6-96e8-5442cedd0313");
user_pref("datareporting.dau.cachedUsageProfileID", "e1d1693c-805d-43ba-841e-2e5f303a59c4");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1788318148602");
user_pref("distribution.fedora.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "154.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "DE");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "b1d5d6ed5fe847e69d1f0f4311867780");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.colorway-builtin-themes-cleanup", 1);
user_pref("extensions.databaseSchema", 37);
user_pref("extensions.formautofill.addresses.supported", "detect");
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20260824110141");
user_pref("extensions.lastAppVersion", "154.0");
user_pref("extensions.lastPlatformVersion", "154.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.signatureCheckpoint", 1);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"18cc1516-de28-4013-8703-c050e2a7e49d\",\"ipp-activator@mozilla.com\":\"80257664-c20a-412d-916d-d8a33a195458\",\"pictureinpicture@mozilla.org\":\"e1118c53-96a2-4bd7-91a7-b32ecdd9c7f8\",\"addons-search-detection@mozilla.com\":\"30952909-ca6d-4f7f-a0bd-de242f30db82\",\"webcompat@mozilla.org\":\"9a310967-e580-48bf-b3e8-4eafebbc122d\",\"newtab@mozilla.org\":\"aa829743-9cee-4189-8499-daffba0b6e34\",\"default-theme@mozilla.org\":\"dce49c20-020c-4343-a337-60f7d7e72d35\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.CHIPS.lastMigrateDatabase", 2);
user_pref("network.cookie.validation.lastEpoch", 1);
user_pref("nimbus.firstUpdateComplete", true);
user_pref("nimbus.migrations.after-remote-settings-update", 0);
user_pref("nimbus.migrations.after-store-initialized", 5);
user_pref("nimbus.migrations.init-started", 1);
user_pref("nimbus.profileId", "cb3b177f-3130-4522-880f-9d3fbcb87eac");
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.bounceTrackingProtection.hasMigratedUserActivationData", true);
user_pref("privacy.clearOnShutdown_v2.formdata", true);
user_pref("privacy.sanitize.clearOnShutdown.hasMigratedToNewPrefs3", true);
user_pref("privacy.sanitize.pending", "[]");
user_pref("privacy.trackingprotection.allow_list.hasMigratedCategoryPrefs", true);
user_pref("privacy.trackingprotection.allow_list.hasUserInteractedWithETPSettings", true);
user_pref("services.settings.base_attachments_url", "https://firefox.settings.services.mozilla.com/v2|https://firefox-settings-attachments.cdn.mozilla.net/");
user_pref("services.sync.engine.addresses.available", true);
user_pref("sidebar.backupState", "{\"command\":\"\",\"panelOpen\":false,\"bookmarksExpandedFolders\":[],\"launcherWidth\":0,\"launcherExpanded\":false,\"launcherVisible\":false}");
user_pref("sidebar.main.tools", "aichat,syncedtabs,history,bookmarks,opentabs");
user_pref("sidebar.nimbus", "upgraded-sidebar-rollout-without-messaging:rollout-treatment");
user_pref("sidebar.revamp", true);
user_pref("sidebar.visibility", "hide-on-close");
user_pref("signon.storage.rust.active", true);
user_pref("signon.storage.rust.enabled", false);
user_pref("toolkit.profiles.newProfileSubmitted", true);
user_pref("toolkit.profiles.storeID", "c6597730");
user_pref("toolkit.startup.last_success", 1788318146);
user_pref("toolkit.telemetry.cachedClientID", "235519c6-6850-4cea-a99a-aac37ecfc1c2");
user_pref("toolkit.telemetry.cachedProfileGroupID", "fd4999cf-c0bf-4277-b6e1-f30f1ba9e7cf");
user_pref("toolkit.telemetry.previousBuildID", "20260824110141");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
